version: "3.9"

name: lab4

services:
  postgres:
    image: postgres:16-alpine
    container_name: lab4-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  users-service:
    build:
      context: ./users-service
    container_name: lab4-users-service
    env_file:
      - ./users-service/.env
    environment:
      PORT: 3001
      FRONTEND_ORIGIN: http://localhost:5173,http://localhost:5174,http://localhost:5175
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/users_db?schema=public
      JWT_SECRET: supersecret
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

  core-service:
    build:
      context: ./core-service
    container_name: lab4-core-service
    env_file:
      - ./core-service/.env
    environment:
      PORT: 3002
      FRONTEND_ORIGIN: http://localhost:5173,http://localhost:5174,http://localhost:5175
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/core_db?schema=public
      JWT_SECRET: supersecret
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      users-service:
        condition: service_started
    ports:
      - "3002:3002"

  mf-catalog:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: mf-catalog
      args:
        MF_ASSET_BASE: http://localhost:5174/
    container_name: lab4-mf-catalog
    depends_on:
      users-service:
        condition: service_started
      core-service:
        condition: service_started
    ports:
      - "5174:80"

  mf-matching:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: mf-matching
      args:
        MF_ASSET_BASE: http://localhost:5175/
    container_name: lab4-mf-matching
    depends_on:
      users-service:
        condition: service_started
      core-service:
        condition: service_started
    ports:
      - "5175:80"

  mf-host:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: mf-host
      args:
        MF_CATALOG_REMOTE: http://localhost:5174/remoteEntry.js
        MF_MATCHING_REMOTE: http://localhost:5175/remoteEntry.js
    container_name: lab4-mf-host
    depends_on:
      mf-catalog:
        condition: service_started
      mf-matching:
        condition: service_started
    ports:
      - "5173:80"

volumes:
  postgres_data:
